# Configuration for the Release Drafter workflow
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'New functions/classes'
    label: 'feature'
  - title: 'Enhancements'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Deprecations'
    label: 'deprecation'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Maintenance'
    label: 'maintenance'
exclude-labels:
  - 'skip-changelog'
change-template: '* $TITLE ([#$NUMBER]($URL) by [@$AUTHOR](https://github.com/$AUTHOR))'
template: |
  [![DOI](https://zenodo.org/badge/DOI/PASTE_DOI_HERE.svg)](https://doi.org/PASTE_DOI_HERE)

  ## Highlights

  *

  $CHANGES

  ## This release contains contributions from:

  $CONTRIBUTORS
